workflows:
    sample-workflow:
        name: Codemagic Sample Workflow
        max_build_duration: 120
        instance_type: mac_mini_m2
        environment:
          xcode: latest
          cocoapods: default
          vars:
            BUNDLE_ID: "com.example.id" # replace with your app bundle
            XCODE_PROJECT: "OpenGpxTracker.xcodeproj" # Replace with your xcodeproj name
            XCODE_SCHEME: "OpenGpxTracker" # Replace with your project name
          ios_signing:
            distribution_type: app_store # or: ad_hoc | development | enterprise
            bundle_identifier: com.example.id
